name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v2
      - name: Build
        run: cd server && cargo +nightly build --verbose
      - name: Run tests
        run: cd server && cargo +nightly test --verbose
